### ISSUE TITLE
J'ai un gros problème

### ISSUE THREAD

**Issue by MRandl** [LilianChesneau/ProjetS1#1]
alors comme ça on spam mon feed github ?
vous vous croyez où la

**Comment by MrZaiko** [comment]
N'importe quoi, GitHub, c'est plus ce que c'était.

**Comment by ChesneauCiccarelli** [comment]
Bonjour, Bonsoir, 

Je me permets de vous répondre en de la part de toute l'équipe Women's Work pour vous présenter nos plus sincère excuses pour la gêne occasionnée. Cependant, nous pouvons travaillez mains dans la main pour résoudre ce problème que vous avez. Je ne saurais trop vous recommander de ne plus utiliser GitHub pour éviter tout contact avec votre feed GitHub.

Cordialement, l'équipe Women's Work.

**Comment by MRandl** [comment]
Bonsoir, 
Bien que je comprenne que l'équipe intégralement masculine de Women's Work se définisse dans l'inclusion et le streamlining progressif et révolutionnaire de la blockchain, et fasse preuve d'un leadership sans faille dans la négociation technique des partenariats sans oublier son dynamisme dans le marché du B2B2C agile orienté-solution, 
je crains malheureusement que la synergie produit-client n'ait atteint un point de non-retour dans son "diversity empowerment" au point de manquer la convergence de l'extension horizontale de l'entreprise, qui préfère pivoter.
Vous êtes virés.
Cordialement,
Jean-Banquier

**Comment by ChesneauCiccarelli** [comment]
Bonjour, Bonsoir,

Je vois que vous avez clos ce problème. Ravi de vous avoir apporté les solutions nécessaires à son évolution. L'équipe entièrement non genrée de Women's Work vous souhaites d'excellentes fêtes de fins d'années.

Cordialement, l'équipe Women's Work.
